config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
          # get 'import', to: 'passwords#import'
          post 'import', to: 'passwords#import'
          resources :passwords, :only => [:index, :show]
    end
  end



  resources :users do
    get 'import', :on => :collection
  end

  resources :uploads
  resources :passwords
  resources :users, :constraints => { :id => /.*/ }
  resources :vendors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#create',  as: :create_login

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/downloads/:id', to: 'uploads#download'

  resources :sessions, only: [:create, :destroy]

  resources :uploads do
    member do

      put 'rerun'

    end
  end

  resources :vendors do
    member do

      get 'remove_logo'

    end
  end



  # root 'users#show'
  root 'login#index'
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :passwords;
  has_many :uploads;
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/logos/original/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  before_destroy :cleanup

  enum showto: { passwords: 0, everyone: 1, students: 2, staff: 3, admin: 4 }


  def cleanup
    #remove logos
    Vendor.find(id).logo.destroy
    #remove uploads
    Upload.where(:vendor_id => self.id).destroy_all
    #remove passwords
    Password.where(:vendor_id => self.id).destroy_all

  end

  def remove_logo
    self.logo.destroy
    self.logo.clear
    self.save
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy, :remove_logo]

  # GET /vendors
  # GET /vendors.json
  def index
    authorize Vendor, :index?
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    authorize Vendor, :show?
    @upload = Upload.new
    @upload.vendor_id = @vendor.id
  end

  # GET /vendors/new
  def new
    authorize Vendor, :new?
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
    authorize Vendor, :edit?
  end

  # POST /vendors
  # POST /vendors.json
  def create
    authorize Vendor, :create?
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    authorize Vendor, :update?
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    authorize Vendor, :destroy?
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_logo
    authorize Vendor, :update?
    @vendor.remove_logo
    respond_to do |format|
      format.html { redirect_to @vendor, notice: 'Vendor Logo was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:title, :link, :logo, :logonform, :showto)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(vendor) do |f| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="card text-center" style="margin-top:10px;">
    <div class="card-header">
      <%= action_name.titleize %> Vendor
    </div>
    <div class="card-block">

      <div class="form-group">
        <%= f.label :title, :class => "col-xs-2 col-form-label", :for => "vendor[title]" %>
        <div class="col-xs-10">
          <%= f.text_field :title, :class => "form-control"  %>

        </div>
      </div>

      <div class="form-group">
        <%= f.label :link, :class => "col-xs-2 col-form-label", :for => "vendor[link]" %>

        <div class="col-xs-10">
          <%= f.text_field :link, :class => "form-control"  %>

        </div>
      </div>




      <div class="form-group">
        <%= f.label :showtoall, 'Show To ', :class => "col-xs-2 ", :for => "vendor[showtoall]" %>

        <div class="col-xs-10">
            <%= f.select(:showto, options_for_select(Vendor.showtos.keys.to_a, vendor.showto), {}, { :class => "form-control"}) %>
        </div>
      </div>





      <div class="actions">
        <%= f.submit :class => "btn btn-primary btn-block" %>
      </div>

    </div>


  </div>



<% end %>

app/views/vendors/_logonform.html.erb
<%= form_for(vendor) do |f| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





    <%= f.hidden_field :vendor_id, :value => vendor.id%>


    <div class="form-group">

      <%= f.label 'HTML Logon form', :class => " col-form-label", :for => "vendor[form]" %>

        <%= f.text_area :logonform, rows: 10, :class => "form-control"  %>


    </div>


  <div class="actions text-center">
    <%= f.submit 'Upload Form', :class => 'btn btn-default'  %>
  </div>
<% end %>

app/views/vendors/_picture_form.html.erb
<%= form_for(vendor) do |f| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





    <%= f.hidden_field :vendor_id, :value => vendor.id%>


    <div class="form-group">

      <%= f.label 'New Logo', :class => " col-form-label", :for => "vendor[file]" %>

        <!-- <%= f.text_field :title, :class => "form-control"  %> -->
        <%= f.file_field :logo, as: :file, :class => "form-control"  %>

    </div>


  <div class="actions text-center">
    <%= f.submit 'Upload New Logo', :class => 'btn btn-default'  %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<!-- <h1>Editing Vendor</h1> -->

<%= render 'form', vendor: @vendor %>

<div class="text-center">
  <%= link_to 'Show', @vendor, :class => "btn btn-secondary" %> |
  <%= link_to 'Back', vendors_path, :class => "btn btn-secondary" %>
</div>

app/views/vendors/index.html.erb
<div class="card" style="margin-top:10px;">
  <div class="card-header">
    Vendors
  </div>
  <div class="card-block ">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Link</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @vendors.each do |vendor| %>
          <tr>
            <td><%= vendor.title %></td>
            <td style="max-width:200px; word-wrap:break-word;"><a href="<%= vendor.link %>" target="_blank" ><%= vendor.link %><a></td>
            <td><%= link_to 'Show', vendor %></td>
            <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
            <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<div class="text-center">

  <%= link_to 'New Vendor', new_vendor_path, :class => 'btn btn-primary' %>

</div>

app/views/vendors/new.html.erb
<!-- <h1>New Vendor</h1> -->

<%= render 'form', vendor: @vendor %>

<div class="text-center">

  <%= link_to 'Back', vendors_path, :class => "btn btn-secondary" %>
</div>

app/views/vendors/show.html.erb
<h3>Info</h3>
<div class="card " style="margin-top:10px;">
  <div class="card-header text-center">
    Vendor
  </div>
  <div class="card-block">

    <div class="form-group">
      <label for="example-text-input" class="col-xs-2 col-form-label">Title</label>
      <div class="col-xs-10">
        <label class="form-control" id="example-text-input"><%= @vendor.title %></label>

      </div>
    </div>

    <div class="form-group">
      <label for="example-text-input" class="col-xs-2 col-form-label">Link</label>

      <div class="col-xs-10  ">
        <label class="form-control" id="example-text-input"><a href="<%= @vendor.link %>"><%= @vendor.link %></a></label>

      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 " for="vendor[showtoall]">Show To </label>

      <div class="col-xs-10">
        <%= @vendor.showto %>

      </div>
    </div>





  </div>




  <div class="card-footer text-muted text-center">
    <%= link_to 'Edit', edit_vendor_path(@vendor) %> |
    <%= link_to 'Back', vendors_path %>
  </div>
</div>



<hr/>


<h3>Logo</h3>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <div class="card  text-center">
      <div class="card-header text-center">
        Preview
      </div>
      <div class="card-block">
        <img src="<%= @vendor.logo.url(:medium) %>" alt="<%= @vendor.title %> Logo" />

      </div>

      <div class="card-footer text-muted text-center">
        <div class=""><%= link_to 'Remove Logo', remove_logo_vendor_path(@vendor) %></div>
      </div>
    </div>
  </div>

  <div class=" col-xs-12 col-md-6">
    <div class="card">
      <div class="card-header text-center">
        Logo Form
      </div>
      <div class="card-block">
        <%= render 'picture_form' , vendor: @vendor %>
      </div>
    </div>
  </div>
</div>


<hr/>

<h3 class="clearfix">Passwords</h3>


<div class="card ">
  <div class="card-header text-center">
    Passwords Form
  </div>
  <div class="card-block">
    <%= render 'uploads/form' , upload: @upload %>
  </div>
</div>

<hr/>

<h3 class="clearfix">Vendor Logon form</h3>


<div class="card ">
  <div class="card-header text-center">
    Vendor Logon form
  </div>
  <div class="card-block">
    <%= render 'logonform' , vendor: @vendor %>
  </div>
</div>