config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
          # get 'import', to: 'passwords#import'
          post 'import', to: 'passwords#import'
          resources :passwords, :only => [:index, :show]
    end
  end



  resources :users do
    get 'import', :on => :collection
  end

  resources :uploads
  resources :passwords
  resources :users, :constraints => { :id => /.*/ }
  resources :vendors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#create',  as: :create_login

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/downloads/:id', to: 'uploads#download'

  resources :sessions, only: [:create, :destroy]

  resources :uploads do
    member do

      put 'rerun'

    end
  end

  resources :vendors do
    member do

      get 'remove_logo'

    end
  end



  # root 'users#show'
  root 'login#index'
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :vendor
  enum status_code: { uploaded: 0, processing: 1, completed: 2, canceled: 3,  error: 4}

  has_attached_file :file, :path => "#{Rails.root}/non-public/uploads/:attachment/:id/:style/:basename.:extension",
                            :url => '/downloads/:id'
  validates_attachment_content_type :file, :content_type => ['text/csv','text/comma-separated-values','text/csv','application/csv','application/excel','application/vnd.ms-excel','application/vnd.msexcel','text/anytext','text/plain']

  validates :file, presence: true

  after_save :create_process

  before_destroy :delete_file

  def delete_file
    Upload.find(self.id).file.destroy
  end

  def create_process
		system "rake import_vendor_info UPLOAD_ID=#{self.id} &"
		# call_rake :import_resorces, :upload_id => self.id
	end

  def rerun
    self.status_code = 0
    self.save
  end


  def uploadPasswords()
    begin
      self.update_columns(status_code: 1)
      require 'csv'
      CSV.foreach(self.file.path) do |row|
        # /user = User.find_by_email(row[0])

        # if user != nil
          # password = Password.where("user_id = ? AND vendor_id = ? ", user.id,self.vendor_id).first
          # password = Password.new if password == nil
          # password.vendor_id = self.vendor_id;
          # password.user_id = user.id
          # password.username = row[1]
          # password.password = row[2]
          # password.save
          Password.import(self.vendor_id, row[0], row[1], row[2])

        # end

      end
      self.update_columns(status_code: 2)

      self.update_columns(comment: "Completed successfully")

    rescue Exception => e
      self.update_columns(status_code: 4)

      self.update_columns(comment: "#{e.message}\n\n#{e.backtrace.inspect}")

    end
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy, :rerun]

  # GET /uploads
  # GET /uploads.json
  def index
    authorize Upload, :index?
    @uploads = Upload.all.order('created_at DESC').limit(100)
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    authorize @upload, :show?
  end

  # GET /uploads/new
  def new
    authorize Upload, :new?
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
    authorize  @upload, :edit?
  end

  # POST /uploads
  # POST /uploads.json
  def create
    authorize Upload, :create?
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    authorize @upload, :update?
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    authorize @upload, :destroy?
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def rerun
    authorize Upload, :rerun?
    if @upload.rerun
      respond_to do |format|
        format.html { redirect_to uploads_url, notice: 'Upload was rerun successfully.' }
        format.json { head :no_content }
      end
    end
  end

  def download
    authorize Upload, :download?
    send_file Upload.find(params[:id]).file.path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
        params.require(:upload).permit(:vendor_id, :file, :status_code, :id)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(upload) do |f| %>
  <% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" >
    <%= f.hidden_field :vendor_id, :value => upload.vendor_id%>
    <%= f.label 'Vendor', :class => " col-form-label", :for => "title" %>

    <label class="form-control" id="title"><%= upload.vendor.title  if upload.vendor != nil %></label>


  </div>

  <div class="form-group">

    <%= f.label 'Select CSV File', :class => " col-form-label", :for => "upload[file]" %>
    <%= f.file_field :file, as: :file , :class => "form-control"%>
    <small id="fileHelp" class="form-text text-muted">CSV File with passwords. No Header need and the columns should be email,username, and password</small>


  </div>

  <div class="actions text-center">
    <%= f.submit 'Create Upload', :class => 'btn btn-default'  %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div class="card" style="margin-top:10px;">
  <div class="card-header">
    Uploads
  </div>
  <div class="card-block ">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Vendor</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @uploads.each do |upload| %>
          <tr>
            <td><%= upload.id %></td>
            <td><%= upload.vendor.title %></td>
            <td><%= upload.created_at %></td>
            <td><%= upload.status_code %></td>
            <td><%= upload.comment %></td>
            <td><%= link_to 'Show', upload %></td>
            <td><%= link_to 'Re-run', rerun_upload_path(upload), :method => :put, data: { :confirm => "Are you sure you want to re-run the import?"} %></td>
            <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload, :class => 'btn btn-primary' %>

<%= link_to 'Back', uploads_path, :class => 'btn btn-primary' %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card " style="margin-top:10px;">
  <div class="card-header text-center">
    Upload
  </div>
  <div class="card-block">
    <div class="form-group" >

      <%= label_tag 'vendor', 'Vendor', :class => "col-xs-2 col-form-label" %>
      <div class="col-xs-10">
        <label class="form-control" id="title"><%= @upload.vendor.title  if @upload.vendor != nil %></label>
      </div>
    </div>

    <div class="form-group" >

      <%= label_tag 'created_at', 'Created at', :class => "col-xs-2  col-form-label" %>
      <div class="col-xs-10">
        <label class="form-control" id="created_at"><%= @upload.created_at %></label>
      </div>
    </div>

    <div class="form-group">

      <%= label_tag 'file', 'File Name', :class => "col-xs-2  col-form-label" %>

      <div class="col-xs-10">
        <label class="form-control" id="file"><a href="<%= @upload.file %>" ><%= "#{request.base_url}#{@upload.file}" %></a></label>
        <small id="fileHelp" class="form-text text-muted">CSV File with passwords. No Header need and the columns should be email,username, and password</small>
      </div>

    </div>

    <div class="form-group">

      <%= label_tag 'status', 'Status', :class => "col-xs-2  col-form-label" %>

      <div class="col-xs-10">
        <label class="form-control" id="status"><%= @upload.status_code %></label>
      </div>

    </div>



    <div class="text-center">
      <%= link_to 'Destroy', @upload, method: :delete, data: { confirm: 'Are you sure you want to remove the file?' } , :class => 'btn btn-secondary'%> |
      <td><%= link_to 'Re-run', rerun_upload_path(@upload), :method => :put, data: { :confirm => "Are you sure you want to re-run the import?"}, :class => 'btn btn-secondary' %></td>
      <%= link_to 'Back', uploads_path, :class => 'btn btn-secondary' %>
    </div>
  </div>
</div>