config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
          # get 'import', to: 'passwords#import'
          post 'import', to: 'passwords#import'
          resources :passwords, :only => [:index, :show]
    end
  end



  resources :users do
    get 'import', :on => :collection
  end

  resources :uploads
  resources :passwords
  resources :users, :constraints => { :id => /.*/ }
  resources :vendors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#create',  as: :create_login

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/downloads/:id', to: 'uploads#download'

  resources :sessions, only: [:create, :destroy]

  resources :uploads do
    member do

      put 'rerun'

    end
  end

  resources :vendors do
    member do

      get 'remove_logo'

    end
  end



  # root 'users#show'
  root 'login#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mypuhsd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-faded navbar-custom">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <a class="navbar-brand" href="/">MyPUHSD</a>

          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <% if policy(User).index? %>
                  <%= link_to "Users".html_safe, users_path, :class => 'btn' %>
                <% end %>
              </li>
              <li class="nav-item">
                <% if policy(Vendor).index? %>
                  <%= link_to "Vendors".html_safe, vendors_path, :class => 'btn' %>
                <% end %>
              </li>
              <li class="nav-item">
                <% if policy(Upload).index? %>
                  <%= link_to "Uploads".html_safe, uploads_path, :class => 'btn' %>
                <% end %>
              </li>
              <li class="nav-item">
                <% if policy(User).import? %>
                  <%= link_to "<i class='fa fa-refresh'></i> Full LDAP Sync".html_safe, import_users_path, :method => :get, :class => 'btn' %>
                <% end %>
              </li>
            </ul>
            <span class="navbar-text">
              <% if current_user %>
                Signed in as <strong><%= link_to current_user.firstname, user_path(current_user) %></strong>!
                <%= link_to "Sign out", signout_path, id: "sign_out", class: "navbar-link" %>
              <% else %>
                <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "navbar-link" %>
              <% end %>
            </span>
          </div>
        </nav>
      </header>








    <div class="container">
      <% flash.each do |msg_type, message| %>
        <%= content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do %>
          <%= content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do %>
            <%= content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true) %>
            <%= content_tag(:span, 'Close', class: 'sr-only') %>
          <% end %>
          <%= message %>
        <% end %>
      <% end %>


      <%= yield %>
    </div>
  </body>
</html>